name: lseg1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  #- plyfile=0.8.1
  - python=3.8
  - pip=22.3.1
  - pytorch=1.12.1
  #- torch #=1.13.0+cu117
  - torchaudio=0.12.1
  - torchvision=0.13.1
  #- torchvision #=0.14.0+cu117
  - tqdm
  - pip:
    #- setuptools
    #- torch
    #- torchvision
    #- pytorch-lightning
    - opencv-python
    - imageio
    - ftfy
    - regex
    - tqdm
    - git+https://github.com/openai/CLIP.git
    - altair
    - streamlit
    - protobuf
    - timm
    - tensorboardX
    - matplotlib
    - test-tube
    - wandb
    - torchmetrics
    - scikit-image
    - scikit-learn
    - git+https://github.com/zhanghang1989/PyTorch-Encoding/
    #- torch
    #- torchvision
    - setuptools==59.5.0
    - pyquaternion
    - plyfile
    - pytransform3d
    - einops==0.4.1
    - kornia==0.6.5
    - pytorch-lightning==1.6.5
    - matplotlib==3.5.2
    - opencv-python==4.6.0.66
    - lpips
    - imageio
    - imageio-ffmpeg
    - jupyter
    - scipy
    - pymcubes
    - trimesh
    - dearpygui
