edit:
  objects: ["car", "tree", "building", "sidewalk", "road"]
  operations: "color_func" 
  colorFunc: "lambda color: color[..., [2,1,0]]" # define your color changing function here
  targets: "car" # the target object should be chosen from the object list
  threshold: 0.198 # leave it empty if using argmax
