edit:
  objects: ["car", "tree", "building", "sidewalk", "road"]
  operations: "deletion" 
  targets: "car" # the target object should be chosen from the object list
  threshold: 0.198 # leave it empty if using argmax

